[features]
seeds = false
skip-lint = false

[programs.devnet]
firethree = "CMDqkbpJ6L4US5FXSFB23hwQGtPJAQrKqvBf2kaJN8BD"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"
