[features]
seeds = false
skip-lint = false

[programs.devnet]
firethree = "Fire3T9ABT33UYoVJZwWUnbPR3rgoVw98y82UgHZ8Bm"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"
